/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/airplane.glb --output src/game/models/Airplane.jsx --root public --keepnames --keepgroups --meta --shadows --precision 7 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/airplane.glb')
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blender_osm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
          glTF2ExportSettings: { export_animations: 0, export_apply: 0, export_extras: 1, export_morph: 0, export_skins: 0 },
        }}>
        <group name="seat_1" position={[0, 0.2208842, -0.3264364]} userData={{ name: 'seat_1', data: 'seat', seat_type: 'driver', entry_points: 'entrance_1;entrance_2' }} />
        <group name="entrance_2" position={[0.6502519, -0.2656898, -0.4621046]} userData={{ name: 'entrance_2' }} />
        <group name="entrance_1" position={[-0.6502519, -0.2656898, -0.4621046]} userData={{ name: 'entrance_1' }} />
        <group name="Empty" position={[-0.019243, 0.7054321, -0.3637531]} userData={{ name: 'Empty', data: 'camera' }} />
        <mesh name="body" castShadow receiveShadow geometry={nodes.body.geometry} material={materials.Airplane} position={[0, 0.0921799, 0.0686227]} userData={{ name: 'body' }}>
          <group name="aileron_parentL" position={[1.255586, 0.1740299, -0.1837715]} rotation={[-0.0000082, 1.5526582, -Math.PI / 2]} userData={{ name: 'aileron_parent.L' }}>
            <mesh name="aileronL" castShadow receiveShadow geometry={nodes.aileronL.geometry} material={materials.Airplane} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'aileron.L', data: 'aileron', side: 'left' }} />
          </group>
          <group name="aileron_parentR" position={[-1.255586, 0.1740299, -0.1837715]} rotation={[-Math.PI, 1.5526483, 1.5707906]} userData={{ name: 'aileron_parent.R' }}>
            <mesh name="aileronR" castShadow receiveShadow geometry={nodes.aileronR.geometry} material={materials.Airplane} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'aileron.R', data: 'aileron', side: 'right' }} />
          </group>
          <group name="elevator_parentL" position={[0.4358847, 0.3343941, -1.2685606]} rotation={[-Math.PI, 1.3623175, Math.PI / 2]} userData={{ name: 'elevator_parent.L' }}>
            <mesh name="elevatorL" castShadow receiveShadow geometry={nodes.elevatorL.geometry} material={materials.Airplane} rotation={[Math.PI / 2, 1e-7, Math.PI / 2]} userData={{ name: 'elevator.L', data: 'elevator' }} />
          </group>
          <group name="elevator_parentR" position={[-0.4358847, 0.3343941, -1.2685606]} rotation={[-7e-7, 1.3623175, -Math.PI / 2]} userData={{ name: 'elevator_parent.R' }}>
            <mesh name="elevatorR" castShadow receiveShadow geometry={nodes.elevatorR.geometry} material={materials.Airplane} rotation={[Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'elevator.R', data: 'elevator' }} />
          </group>
          <group name="rotor_parent" position={[0, 0.1948569, 0.7717311]} userData={{ name: 'rotor_parent' }}>
            <mesh name="rotor" castShadow receiveShadow geometry={nodes.rotor.geometry} material={materials.Airplane} rotation={[0, Math.PI / 2, 0]} scale={1.1537337} userData={{ name: 'rotor', data: 'rotor' }} />
          </group>
          <group name="rudder_parent" position={[0, 0.9191867, -1.3419647]} rotation={[1.3154258, -1e-7, Math.PI]} userData={{ name: 'rudder_parent' }}>
            <mesh name="rudder" castShadow receiveShadow geometry={nodes.rudder.geometry} material={materials.Airplane} rotation={[Math.PI / 2, 2e-7, Math.PI / 2]} userData={{ name: 'rudder', data: 'rudder' }} />
          </group>
        </mesh>
        <mesh name="wheel_fl" castShadow receiveShadow geometry={nodes.wheel_fl.geometry} material={materials.Wheel} position={[0, -0.1509271, 0.4923996]} userData={{ name: 'wheel_fl', steering: 'true', data: 'wheel' }} />
        <mesh name="wheel_fl001" castShadow receiveShadow geometry={nodes.wheel_fl001.geometry} material={materials.Wheel} position={[0.2063109, -0.1519533, -0.2867631]} userData={{ name: 'wheel_fl.001', data: 'wheel' }} />
        <mesh name="wheel_fl002" castShadow receiveShadow geometry={nodes.wheel_fl002.geometry} material={materials.Wheel} position={[-0.206311, -0.1519533, -0.2867631]} userData={{ name: 'wheel_fl.002', data: 'wheel' }} />
        <mesh name="Cube008" castShadow receiveShadow geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[0, 0.2952009, -0.2724662]} scale={[0.2930114, 0.2695051, 1.1128198]} userData={{ name: 'Cube.008', data: 'collision', shape: 'box' }} />
        <mesh name="Cube013" castShadow receiveShadow geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[1.0370322, 0.2760242, 0.0253231]} scale={[0.74402, 0.0459855, 0.2433757]} userData={{ name: 'Cube.013', data: 'collision', shape: 'box' }} />
        <mesh name="Cube014" castShadow receiveShadow geometry={nodes.Cube014.geometry} material={nodes.Cube014.material} position={[-1.0370322, 0.2760242, 0.0253231]} scale={[0.74402, 0.0459855, 0.2433757]} userData={{ name: 'Cube.014', data: 'collision', shape: 'box' }} />
        <mesh name="Cube009" castShadow receiveShadow geometry={nodes.Cube009.geometry} material={nodes.Cube009.material} position={[0, 0.7030616, -1.0153455]} scale={[0.2930114, 0.1383557, 0.3699404]} userData={{ name: 'Cube.009', data: 'collision', shape: 'box' }} />
        <mesh name="Cube010" castShadow receiveShadow geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[0, 1.1038163, -1.1107424]} scale={[0.0301382, 0.2623988, 0.2745433]} userData={{ name: 'Cube.010', data: 'collision', shape: 'box' }} />
        <mesh name="Cube011" castShadow receiveShadow geometry={nodes.Cube011.geometry} material={nodes.Cube011.material} position={[0.5209367, 0.4570408, -1.1234717]} scale={[0.2279253, 0.02358, 0.2618141]} userData={{ name: 'Cube.011', data: 'collision', shape: 'box' }} />
        <mesh name="Cube012" castShadow receiveShadow geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[-0.5209367, 0.4570408, -1.1234717]} scale={[0.227925, 0.02358, 0.2618141]} userData={{ name: 'Cube.012', data: 'collision', shape: 'box' }} />
        <mesh name="Sphere001" castShadow receiveShadow geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[0, 0.2960142, 0.5715725]} scale={0.268781} userData={{ name: 'Sphere.001', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere000" castShadow receiveShadow geometry={nodes.Sphere000.geometry} material={nodes.Sphere000.material} position={[0, 0.2960142, -1.1165049]} scale={0.268781} userData={{ name: 'Sphere.000', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere002" castShadow receiveShadow geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} position={[-1.5420245, 0.2960142, 0.0256791]} scale={0.2390278} userData={{ name: 'Sphere.002', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere003" castShadow receiveShadow geometry={nodes.Sphere003.geometry} material={nodes.Sphere003.material} position={[1.5420243, 0.2960142, 0.0256791]} scale={0.2390278} userData={{ name: 'Sphere.003', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere004" castShadow receiveShadow geometry={nodes.Sphere004.geometry} material={nodes.Sphere004.material} position={[0, 1.097434, -1.1165049]} scale={0.268781} userData={{ name: 'Sphere.004', shape: 'sphere', data: 'collision' }} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/airplane.glb')
