/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/boxman.glb --output src/game/models/Boxman.tsx --root public --keepnames --keepgroups --meta --shadows --precision 7 --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph, type ThreeElements } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

export const MODEL_PATH = '/assets/boxman.glb'

type ActionName = 'close_door_sitting_left' | 'close_door_sitting_right' | 'close_door_standing_left' | 'close_door_standing_right' | 'driving' | 'drop_idle' | 'drop_running' | 'drop_running_roll' | 'enter_airplane_left' | 'enter_airplane_right' | 'falling' | 'idle' | 'jump_idle' | 'jump_running' | 'open_door_standing_left' | 'open_door_standing_right' | 'reset' | 'rotate_left' | 'rotate_right' | 'run' | 'sit_down_left' | 'sit_down_right' | 'sitting' | 'sitting_shift_left' | 'sitting_shift_right' | 'sprint' | 'stand_up_left' | 'stand_up_right' | 'start_back_left' | 'start_back_right' | 'start_forward' | 'start_left' | 'start_right' | 'stop'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    game_man: THREE.SkinnedMesh
    root: THREE.Bone
  }
  materials: {
    Boxman: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: ThreeElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(MODEL_PATH)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          vs: {
            export_list: [
              { name: 'Armature.dmx', ob_type: 'ACTION', icon: 'NLA', item_name: 'Armature' },
              { name: 'game_man.dmx', ob_type: 'OBJECT', icon: 'OUTLINER_OB_MESH', item_name: 'game_man' },
              { name: 'shape2_IK.dmx', ob_type: 'OBJECT', icon: 'OUTLINER_OB_MESH', item_name: 'shape2_IK' },
              { name: 'shape2_IK.001.dmx', ob_type: 'OBJECT', icon: 'OUTLINER_OB_MESH', item_name: 'shape2_IK.001' },
              { name: 'shape_IK.dmx', ob_type: 'OBJECT', icon: 'OUTLINER_OB_MESH', item_name: 'shape_IK' },
              { name: 'Sphere.dmx', ob_type: 'OBJECT', icon: 'OUTLINER_OB_MESH', item_name: 'Sphere' },
            ],
          },
          threeExportSettings: { bones: 1, mixColors: 0, indexType: 'Uint16Array', customProperties: 0, lights: 0, frameIndexAsTime: 0, morphTargets: 0, hierarchy: 1, exportTextures: 1, embedAnimation: 1, skinning: 1, extraVertexGroups: '', compression: 'None', colors: 0, faceMaterials: 1, vertices: 1, influencesPerVertex: 2, textureFolder: '', tracks: 0, scene: 1, animations: 'pose', materials: 1, blendShapes: 0, applyModifiers: 0, embedTextures: 0, enablePrecision: 0, bake_tracks: 0, maps: 1, precision: 6, logging: 'disabled', frameStep: 1, uvs: 1, scale: 1, normals: 1, cameras: 0, faces: 1, indent: 1, geometryType: 'geometry' },
          blender_osm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
          glTF2ExportSettings: { export_all_influences: 0, export_apply: 1, export_colors: 0, export_def_bones: 1, export_extras: 1, export_frame_range: 0, export_morph: 0, use_selection: 0 },
        }}>
        <group name="Armature" scale={0.38} userData={{ name: 'Armature' }}>
          <primitive object={nodes.root} />
          <skinnedMesh name="game_man" geometry={nodes.game_man.geometry} material={materials.Boxman} skeleton={nodes.game_man.skeleton} userData={{ gaylord: 1, name: 'game_man' }} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_PATH)
