/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/boxman.glb --output src/game/models/Boxman.jsx --root public --keepnames --keepgroups --meta --shadows --precision 7 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/assets/boxman.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          vs: {
            export_list: [
              { name: 'Armature.dmx', ob_type: 'ACTION', icon: 'NLA', item_name: 'Armature' },
              { name: 'game_man.dmx', ob_type: 'OBJECT', icon: 'OUTLINER_OB_MESH', item_name: 'game_man' },
              { name: 'shape2_IK.dmx', ob_type: 'OBJECT', icon: 'OUTLINER_OB_MESH', item_name: 'shape2_IK' },
              { name: 'shape2_IK.001.dmx', ob_type: 'OBJECT', icon: 'OUTLINER_OB_MESH', item_name: 'shape2_IK.001' },
              { name: 'shape_IK.dmx', ob_type: 'OBJECT', icon: 'OUTLINER_OB_MESH', item_name: 'shape_IK' },
              { name: 'Sphere.dmx', ob_type: 'OBJECT', icon: 'OUTLINER_OB_MESH', item_name: 'Sphere' },
            ],
          },
          threeExportSettings: { bones: 1, mixColors: 0, indexType: 'Uint16Array', customProperties: 0, lights: 0, frameIndexAsTime: 0, morphTargets: 0, hierarchy: 1, exportTextures: 1, embedAnimation: 1, skinning: 1, extraVertexGroups: '', compression: 'None', colors: 0, faceMaterials: 1, vertices: 1, influencesPerVertex: 2, textureFolder: '', tracks: 0, scene: 1, animations: 'pose', materials: 1, blendShapes: 0, applyModifiers: 0, embedTextures: 0, enablePrecision: 0, bake_tracks: 0, maps: 1, precision: 6, logging: 'disabled', frameStep: 1, uvs: 1, scale: 1, normals: 1, cameras: 0, faces: 1, indent: 1, geometryType: 'geometry' },
          blender_osm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
          glTF2ExportSettings: { export_all_influences: 0, export_apply: 1, export_colors: 0, export_def_bones: 1, export_extras: 1, export_frame_range: 0, export_morph: 0, use_selection: 0 },
        }}>
        <group name="Armature" scale={0.38} userData={{ name: 'Armature' }}>
          <primitive object={nodes.root} />
          <skinnedMesh name="game_man" geometry={nodes.game_man.geometry} material={materials.Boxman} skeleton={nodes.game_man.skeleton} userData={{ gaylord: 1, name: 'game_man' }} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/boxman.glb')
