/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/bus_compressed.glb --output src/game/models/BusCompressed.tsx --root public --keepnames --keepgroups --meta --shadows --precision 7 --types 
Author: mamont nikita (https://sketchfab.com/mamontnikita62)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bus-c1371690104c47649df34180c0b5f7c1
Title: bus
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

export const MODEL_PATH = '/assets/bus_compressed.glb'

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh
    Object_7: THREE.Mesh
    Object_9: THREE.Mesh
    Object_11: THREE.Mesh
    Object_13: THREE.Mesh
    Object_15: THREE.Mesh
    Object_17: THREE.Mesh
    Object_19: THREE.Mesh
    Object_21: THREE.Mesh
    Object_23: THREE.Mesh
    Object_25: THREE.Mesh
    Object_27: THREE.Mesh
    Object_29: THREE.Mesh
    Object_33: THREE.Mesh
    Object_37: THREE.Mesh
  }
  materials: {
    backlght: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    body: THREE.MeshStandardMaterial
    body_blk: THREE.MeshStandardMaterial
    chrome: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
    glassblk: THREE.MeshStandardMaterial
    headlght: THREE.MeshStandardMaterial
    interior: THREE.MeshStandardMaterial
    mirror: THREE.MeshStandardMaterial
    nplate: THREE.MeshStandardMaterial
    plastic: THREE.MeshStandardMaterial
    rearlght: THREE.MeshStandardMaterial
    turnlght: THREE.MeshStandardMaterial
    wheel: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(MODEL_PATH) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Object_5" castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.backlght} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_5' }} />
        <mesh name="Object_7" castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.black} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_7' }} />
        <mesh name="Object_9" castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials.body} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_9' }} />
        <mesh name="Object_11" castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.body_blk} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_11' }} />
        <mesh name="Object_13" castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials.chrome} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_13' }} />
        <mesh name="Object_15" castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials.glass} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_15' }} />
        <mesh name="Object_17" castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials.glassblk} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_17' }} />
        <mesh name="Object_19" castShadow receiveShadow geometry={nodes.Object_19.geometry} material={materials.headlght} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_19' }} />
        <mesh name="Object_21" castShadow receiveShadow geometry={nodes.Object_21.geometry} material={materials.interior} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_21' }} />
        <mesh name="Object_23" castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials.mirror} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_23' }} />
        <mesh name="Object_25" castShadow receiveShadow geometry={nodes.Object_25.geometry} material={materials.nplate} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_25' }} />
        <mesh name="Object_27" castShadow receiveShadow geometry={nodes.Object_27.geometry} material={materials.plastic} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_27' }} />
        <mesh name="Object_29" castShadow receiveShadow geometry={nodes.Object_29.geometry} material={materials.rearlght} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_29' }} />
        <mesh name="Object_33" castShadow receiveShadow geometry={nodes.Object_33.geometry} material={materials.turnlght} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_33' }} />
        <mesh name="Object_37" castShadow receiveShadow geometry={nodes.Object_37.geometry} material={materials.wheel} position={[-0.001, -0.001, 0.001]} rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Object_37' }} />
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_PATH)
