/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/car.glb --output src/game/models/Car.tsx --root public --keepnames --keepgroups --meta --shadows --precision 7 --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

export const MODEL_PATH = '/assets/car.glb'

type GLTFResult = GLTF & {
  nodes: {
    body: THREE.Mesh
    Steering_wheel: THREE.Mesh
    door_1: THREE.Mesh
    door_2: THREE.Mesh
    door_3: THREE.Mesh
    door_4: THREE.Mesh
    wheel_fl: THREE.Mesh
    Cylinder001: THREE.Mesh
    wheel_fr: THREE.Mesh
    wheel: THREE.Mesh
    Cube006: THREE.Mesh
    Cube002: THREE.Mesh
    Sphere: THREE.Mesh
    Sphere001: THREE.Mesh
    Sphere002: THREE.Mesh
    Sphere004: THREE.Mesh
    Sphere007: THREE.Mesh
    Sphere003: THREE.Mesh
    Sphere005: THREE.Mesh
    Sphere006: THREE.Mesh
    Sphere008: THREE.Mesh
    Sphere009: THREE.Mesh
    Sphere010: THREE.Mesh
    Sphere011: THREE.Mesh
  }
  materials: {
    Car: THREE.MeshStandardMaterial
    Wheel: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(MODEL_PATH) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          NWBusyDrawing: '',
          NWLazySource: 'Image Texture',
          NWLazyTarget: 'Principled BSDF',
          NWSourceSocket: 0,
          blender_osm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
          glTF2ExportSettings: { export_animations: 0, export_extras: 1, export_morph: 0, export_skins: 0 },
        }}>
        <group name="seat_1" position={[0.2456998, 0.0551427, 0.0869809]} userData={{ name: 'seat_1', data: 'seat', door_object: 'door_1', seat_type: 'driver', entry_points: 'entrance_1', connected_seats: 'seat_2' }} />
        <group name="seat_3" position={[0.2456998, 0.0551427, -0.4457521]} userData={{ name: 'seat_3', data: 'seat', door_object: 'door_3', seat_type: 'passenger', entry_points: 'entrance_3', connected_seats: 'seat_4' }} />
        <group name="seat_2" position={[-0.2456998, 0.0551427, 0.0869809]} userData={{ name: 'seat_2', data: 'seat', door_object: 'door_2', seat_type: 'passenger', entry_points: 'entrance_2', connected_seats: 'seat_1' }} />
        <group name="seat_4" position={[-0.2456998, 0.0551427, -0.4457521]} userData={{ name: 'seat_4', data: 'seat', seat_type: 'passenger', door_object: 'door_4', connected_seats: 'seat_3', entry_points: 'entrance_4' }} />
        <group name="entrance_1" position={[1.0024033, -0.3581504, -0.0288473]} userData={{ name: 'entrance_1' }} />
        <group name="entrance_3" position={[1.0024033, -0.3581504, -0.6032887]} userData={{ name: 'entrance_3' }} />
        <group name="entrance_4" position={[-1.0024033, -0.3581504, -0.6032887]} userData={{ name: 'entrance_4' }} />
        <group name="entrance_2" position={[-1.0024033, -0.3581504, -0.0288473]} userData={{ name: 'entrance_2' }} />
        <group name="Empty" position={[0.2379739, 0.5228312, -0.0148874]} userData={{ name: 'Empty', data: 'camera' }} />
        <mesh name="body" castShadow receiveShadow geometry={nodes.body.geometry} material={materials.Car} position={[0, 0.0306787, 0.104756]} userData={{ name: 'body' }}>
          <group name="Steer_parent" position={[0.239457, 0.2949362, 0.2270889]} rotation={[0.4876713, 0, 0]} userData={{ name: 'Steer parent' }}>
            <mesh name="Steering_wheel" castShadow receiveShadow geometry={nodes.Steering_wheel.geometry} material={materials.Car} userData={{ name: 'Steering wheel', data: 'steering_wheel' }} />
          </group>
          <mesh name="door_1" castShadow receiveShadow geometry={nodes.door_1.geometry} material={materials.Car} position={[0.6116745, 0.0988545, 0.3823319]} userData={{ name: 'door_1' }} />
          <mesh name="door_2" castShadow receiveShadow geometry={nodes.door_2.geometry} material={materials.Car} position={[-0.6116744, 0.0988545, 0.3823319]} userData={{ name: 'door_2' }} />
          <mesh name="door_3" castShadow receiveShadow geometry={nodes.door_3.geometry} material={materials.Car} position={[0.6116745, 0.0988545, -0.2757166]} userData={{ name: 'door_3' }} />
          <mesh name="door_4" castShadow receiveShadow geometry={nodes.door_4.geometry} material={materials.Car} position={[-0.6116744, 0.0988545, -0.2757166]} userData={{ name: 'door_4' }} />
        </mesh>
        <mesh name="wheel_fl" castShadow receiveShadow geometry={nodes.wheel_fl.geometry} material={materials.Wheel} position={[0.4817224, -0.1234261, 0.8643622]} userData={{ name: 'wheel_fl', steering: 'true', data: 'wheel', drive: 'fwd' }} />
        <mesh name="Cylinder001" castShadow receiveShadow geometry={nodes.Cylinder001.geometry} material={materials.Wheel} position={[0.4817224, -0.123426, -0.7870018]} userData={{ name: 'Cylinder.001', data: 'wheel', drive: 'rwd' }} />
        <mesh name="wheel_fr" castShadow receiveShadow geometry={nodes.wheel_fr.geometry} material={materials.Wheel} position={[-0.4817224, -0.1234261, 0.8643622]} userData={{ name: 'wheel_fr', data: 'wheel', steering: 'true', drive: 'fwd' }} />
        <mesh name="wheel" castShadow receiveShadow geometry={nodes.wheel.geometry} material={materials.Wheel} position={[-0.4817224, -0.1234261, -0.7870021]} userData={{ name: 'wheel', data: 'wheel', drive: 'rwd' }} />
        <mesh name="Cube006" castShadow receiveShadow geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[0, 0.091266, 0.0379971]} scale={[0.6116744, 0.2486556, 1.2101946]} userData={{ name: 'Cube.006', data: 'collision', shape: 'box' }} />
        <mesh name="Cube002" castShadow receiveShadow geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[0, 0.6199503, -0.255213]} scale={[0.541851, 0.2800287, 0.5357179]} userData={{ name: 'Cube.002', data: 'collision', shape: 'box' }} />
        <mesh name="Sphere" castShadow receiveShadow geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[0.3058382, 0.1512866, 0.9430956]} scale={0.305836} userData={{ name: 'Sphere', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere001" castShadow receiveShadow geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[0.2943447, 0.6524726, 0.0329985]} scale={0.30012} userData={{ name: 'Sphere.001', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere002" castShadow receiveShadow geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} position={[-0.2943448, 0.6524725, 0.0329988]} scale={0.30012} userData={{ name: 'Sphere.002', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere004" castShadow receiveShadow geometry={nodes.Sphere004.geometry} material={nodes.Sphere004.material} position={[0.2943447, 0.6524726, -0.5434245]} scale={0.30012} userData={{ name: 'Sphere.004', data: 'collision', shape: 'sphere' }} />
        <mesh name="Sphere007" castShadow receiveShadow geometry={nodes.Sphere007.geometry} material={nodes.Sphere007.material} position={[-0.2943448, 0.6524725, -0.5434242]} scale={0.30012} userData={{ name: 'Sphere.007', data: 'collision', shape: 'sphere' }} />
        <mesh name="Sphere003" castShadow receiveShadow geometry={nodes.Sphere003.geometry} material={nodes.Sphere003.material} position={[-0.3058383, 0.1512866, 0.9430956]} scale={0.305836} userData={{ name: 'Sphere.003', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere005" castShadow receiveShadow geometry={nodes.Sphere005.geometry} material={nodes.Sphere005.material} position={[0.3058382, 0.1512866, -0.8663614]} scale={0.305836} userData={{ name: 'Sphere.005', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere006" castShadow receiveShadow geometry={nodes.Sphere006.geometry} material={nodes.Sphere006.material} position={[-0.3058383, 0.1512866, -0.8663614]} scale={0.305836} userData={{ name: 'Sphere.006', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere008" castShadow receiveShadow geometry={nodes.Sphere008.geometry} material={nodes.Sphere008.material} position={[0.3058382, 0.1512866, -0.2678816]} scale={0.305836} userData={{ name: 'Sphere.008', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere009" castShadow receiveShadow geometry={nodes.Sphere009.geometry} material={nodes.Sphere009.material} position={[-0.3058383, 0.1512866, -0.2678816]} scale={0.305836} userData={{ name: 'Sphere.009', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere010" castShadow receiveShadow geometry={nodes.Sphere010.geometry} material={nodes.Sphere010.material} position={[0.3058382, 0.1512866, 0.3437905]} scale={0.305836} userData={{ name: 'Sphere.010', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere011" castShadow receiveShadow geometry={nodes.Sphere011.geometry} material={nodes.Sphere011.material} position={[-0.3058383, 0.1512866, 0.3437905]} scale={0.305836} userData={{ name: 'Sphere.011', shape: 'sphere', data: 'collision' }} />
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_PATH)
