/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/heli.glb --output src/game/models/Heli.jsx --root public --keepnames --keepgroups --meta --shadows --precision 7 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/heli.glb')
  return (
    <group {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          blender_osm: {
            defaultLevels: [
              { levels: 4, weight: 10 },
              { levels: 5, weight: 40 },
              { levels: 6, weight: 10 },
            ],
          },
          glTF2ExportSettings: { export_animations: 0, export_extras: 1, export_morph: 0, export_skins: 0 },
        }}>
        <group name="Empty002" position={[0.2358117, 0.2011419, 0.1856878]} userData={{ name: 'Empty.002', data: 'camera' }} />
        <group name="seat_1" position={[0.2456998, -0.25515, 0.1612403]} userData={{ name: 'seat_1', data: 'seat', door_object: 'door_L', seat_type: 'driver', connected_seats: 'seat_2', entry_points: 'entrance_1' }} />
        <group name="entrance_1" position={[0.9552897, -0.6730033, -0.0925749]} userData={{ name: 'entrance_1' }} />
        <group name="entrance_2" position={[-0.9552897, -0.6730033, -0.0925749]} userData={{ name: 'entrance_2' }} />
        <group name="seat_2" position={[-0.2456998, -0.25515, 0.1612403]} userData={{ name: 'seat_2', data: 'seat', door_object: 'door_R', seat_type: 'passenger', entry_points: 'entrance_2', connected_seats: 'seat_1' }} />
        <mesh name="Cube" castShadow receiveShadow geometry={nodes.Cube.geometry} material={materials.Heli} position={[-0.0003091, -0.2390185, 0.0969764]} userData={{ name: 'Cube' }}>
          <group name="Empty" position={[0.2281056, 0.714076, -1.6941241]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} userData={{ name: 'Empty' }}>
            <mesh name="Cube002" castShadow receiveShadow geometry={nodes.Cube002.geometry} material={materials.Heli} rotation={[-Math.PI / 2, 0, Math.PI / 2]} userData={{ name: 'Cube.002', data: 'rotor' }} />
          </group>
          <group name="Empty001" position={[0.0003091, 1.1878846, -0.2507854]} rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'Empty.001' }}>
            <mesh name="Cube004_1" castShadow receiveShadow geometry={nodes.Cube004_1.geometry} material={materials.Heli} position={[0, 0, -0.0153379]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} userData={{ name: 'Cube.004', data: 'rotor' }} />
          </group>
          <mesh name="door_L" castShadow receiveShadow geometry={nodes.door_L.geometry} material={materials.Heli} position={[0.5141841, -0.0221149, 0.2909295]} scale={0.5132589} userData={{ name: 'door_L' }} />
          <mesh name="door_R" castShadow receiveShadow geometry={nodes.door_R.geometry} material={materials.Heli} position={[-0.5135659, -0.0221149, 0.2909296]} userData={{ name: 'door_R' }} />
        </mesh>
        <mesh name="Cube006" castShadow receiveShadow geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[0, 0.0384616, -0.1453916]} scale={[0.5333655, 0.7114649, 0.5593937]} userData={{ name: 'Cube.006', data: 'collision', shape: 'box' }} />
        <mesh name="Cube007" castShadow receiveShadow geometry={nodes.Cube007.geometry} material={nodes.Cube007.material} position={[0, 0.4007393, -1.2286377]} scale={[0.2078095, 0.3491873, 0.5238524]} userData={{ name: 'Cube.007', data: 'collision', shape: 'box' }} />
        <mesh name="Cube001" castShadow receiveShadow geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0, 0.0384616, 0.6213377]} scale={[0.0586005, 0.7114649, 0.2073355]} userData={{ name: 'Cube.001', data: 'collision', shape: 'box' }} />
        <mesh name="Cube005" castShadow receiveShadow geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[0.295983, -0.3727644, 0.6213377]} scale={[0.2373825, 0.300239, 0.2073354]} userData={{ name: 'Cube.005', data: 'collision', shape: 'box' }} />
        <mesh name="Cube008" castShadow receiveShadow geometry={nodes.Cube008.geometry} material={nodes.Cube008.material} position={[-0.295983, -0.3727644, 0.6213377]} scale={[0.2373825, 0.300239, 0.2073354]} userData={{ name: 'Cube.008', data: 'collision', shape: 'box' }} />
        <mesh name="Sphere001" castShadow receiveShadow geometry={nodes.Sphere001.geometry} material={nodes.Sphere001.material} position={[0.2858591, -0.4254969, 0.5811667]} scale={0.2475064} userData={{ name: 'Sphere.001', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere000" castShadow receiveShadow geometry={nodes.Sphere000.geometry} material={nodes.Sphere000.material} position={[-0.2858591, -0.4254969, 0.5811667]} scale={0.2475064} userData={{ name: 'Sphere.000', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere002" castShadow receiveShadow geometry={nodes.Sphere002.geometry} material={nodes.Sphere002.material} position={[-0.2858591, -0.4254969, -0.4572788]} scale={0.2475064} userData={{ name: 'Sphere.002', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere003" castShadow receiveShadow geometry={nodes.Sphere003.geometry} material={nodes.Sphere003.material} position={[0.2858591, -0.4254969, -0.4572788]} scale={0.2475064} userData={{ name: 'Sphere.003', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere004" castShadow receiveShadow geometry={nodes.Sphere004.geometry} material={nodes.Sphere004.material} position={[-0.0009039, 0.4772474, -1.5640846]} scale={0.2136875} userData={{ name: 'Sphere.004', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere007" castShadow receiveShadow geometry={nodes.Sphere007.geometry} material={nodes.Sphere007.material} position={[0, 0.1070279, 0.1698119]} scale={0.5748714} userData={{ name: 'Sphere.007', shape: 'sphere', data: 'collision' }} />
        <mesh name="Sphere005" castShadow receiveShadow geometry={nodes.Sphere005.geometry} material={nodes.Sphere005.material} position={[0, 0.6579379, -0.1516147]} scale={0.2475064} userData={{ name: 'Sphere.005', shape: 'sphere', data: 'collision' }} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/heli.glb')
