/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/lowpoly_bus-optimized.glb --output src/game/models/LowpolyBusOptimized.jsx --root public --keepnames --keepgroups --meta --shadows --precision 7 
Author: RyanTree (https://sketchfab.com/x88665577)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lowpoly-bus-eb264cd5dfe54d71b7b92c9702351338
Title: lowpoly bus
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/lowpoly_bus-optimized.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <mesh name="Object_4" castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.material} position={[5.6009579, 5.0652189, -1.6013403]} userData={{ name: 'Object_4' }} />
        <mesh name="Object_5" castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.glass} position={[5.6009579, 5.0652189, -1.6013403]} userData={{ name: 'Object_5' }} />
        <mesh name="Object_6" castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials['car.001']} position={[5.6009579, 5.0652189, -1.6013403]} userData={{ name: 'Object_6' }} />
        <mesh name="Object_7" castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.material_3} position={[5.6009579, 5.0652189, -1.6013403]} userData={{ name: 'Object_7' }} />
        <mesh name="Object_8" castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.orange} position={[5.6009579, 5.0652189, -1.6013403]} userData={{ name: 'Object_8' }} />
        <mesh name="Object_9" castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials['weel.001']} position={[5.6009579, 5.0652189, -1.6013403]} userData={{ name: 'Object_9' }} />
        <mesh name="Object_10" castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials.weel} position={[5.6009579, 5.0652189, -1.6013403]} userData={{ name: 'Object_10' }} />
        <mesh name="Object_11" castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials.car_inside} position={[5.6009579, 5.0652189, -1.6013403]} userData={{ name: 'Object_11' }} />
        <mesh name="Object_12" castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials.sign} position={[5.6009579, 5.0652189, -1.6013403]} userData={{ name: 'Object_12' }} />
        <mesh name="Object_13" castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials.pipe} position={[5.6009579, 5.0652189, -1.6013403]} userData={{ name: 'Object_13' }} />
        <mesh name="Object_14" castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials.handle} position={[5.6009579, 5.0652189, -1.6013403]} userData={{ name: 'Object_14' }} />
        <mesh name="Object_15" castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials.Material} position={[5.6009579, 5.0652189, -1.6013403]} userData={{ name: 'Object_15' }} />
        <mesh name="Object_17" castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials.material} position={[2.6625998, 4.6749258, 7.2368913]} userData={{ name: 'Object_17' }} />
        <mesh name="Object_18" castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials.glass} position={[2.6625998, 4.6749258, 7.2368913]} userData={{ name: 'Object_18' }} />
        <mesh name="Object_19" castShadow receiveShadow geometry={nodes.Object_19.geometry} material={materials.material_3} position={[2.6625998, 4.6749258, 7.2368913]} userData={{ name: 'Object_19' }} />
        <mesh name="Object_21" castShadow receiveShadow geometry={nodes.Object_21.geometry} material={materials.material} position={[2.6625998, 4.6749258, -1.6989188]} userData={{ name: 'Object_21' }} />
        <mesh name="Object_22" castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials.glass} position={[2.6625998, 4.6749258, -1.6989188]} userData={{ name: 'Object_22' }} />
        <mesh name="Object_23" castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials.material_3} position={[2.6625998, 4.6749258, -1.6989188]} userData={{ name: 'Object_23' }} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/lowpoly_bus-optimized.glb')
