/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/low_poly_soviet_nbc_suit.glb --output src/game/models/LowPolySovietNbcSuit.tsx --root public --keepnames --keepgroups --meta --shadows --precision 7 --types 
Author: ICEMAN (https://sketchfab.com/toastandthecity)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-soviet-nbc-suit-8d6ced5d5f124a06a4e40e71513382f3
Title: Low Poly Soviet NBC Suit
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

export const MODEL_PATH = '/assets/low_poly_soviet_nbc_suit.glb'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    White: THREE.MeshStandardMaterial
    Green: THREE.MeshStandardMaterial
    DarkGrey: THREE.MeshStandardMaterial
    suit: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(MODEL_PATH) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Sketchfab_model' }}>
          <group name="root" userData={{ name: 'root' }}>
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'GLTF_SceneRootNode' }}>
              <group name="Main_0" position={[0, 3.929709, 0]} scale={0.8259921} userData={{ name: 'Main_0' }}>
                <mesh name="Object_4" castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.White} userData={{ name: 'Object_4' }} />
                <mesh name="Object_5" castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.Green} userData={{ name: 'Object_5' }} />
                <mesh name="Object_6" castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.DarkGrey} userData={{ name: 'Object_6' }} />
                <mesh name="Object_7" castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.suit} userData={{ name: 'Object_7' }} />
                <mesh name="Object_8" castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials.material} userData={{ name: 'Object_8' }} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_PATH)
