/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/saab901-optimized.glb --output src/game/models/Saab901Optimized.tsx --root public --keepnames --keepgroups --meta --shadows --precision 7 --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

export const MODEL_PATH = '/assets/saab901-optimized.glb'

type GLTFResult = GLTF & {
  nodes: {
    ['Box012_Material_#280_0']: THREE.Mesh
    ['Cylinder007_Material_#280_0']: THREE.Mesh
    ['Cylinder008_Material_#280_0']: THREE.Mesh
    ['Box014_Material_#280_0']: THREE.Mesh
    ['Box015_Material_#280_0']: THREE.Mesh
    ['Box016_Material_#280_0']: THREE.Mesh
    ['Box017_Material_#280_0']: THREE.Mesh
  }
  materials: {
    Material_280: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(MODEL_PATH) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="saab_900glb">
        <mesh name="Box012_Material_#280_0" castShadow receiveShadow geometry={nodes['Box012_Material_#280_0'].geometry} material={materials.Material_280} position={[-0.9426555, 0.0212171, -0.5440258]} scale={[0.0710499, 0.1035446, 0.0709256]} userData={{ name: 'Box012_Material #280_0' }} />
        <mesh name="Cylinder007_Material_#280_0" castShadow receiveShadow geometry={nodes['Cylinder007_Material_#280_0'].geometry} material={materials.Material_280} position={[-0.7273751, -1.2563639, -0.4153645]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.0293221, 0.0293221, 0.0160142]} userData={{ name: 'Cylinder007_Material #280_0' }} />
        <mesh name="Cylinder008_Material_#280_0" castShadow receiveShadow geometry={nodes['Cylinder008_Material_#280_0'].geometry} material={materials.Material_280} position={[-0.7273751, 1.4052462, -0.4153644]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.0293221, 0.0293221, 0.0160142]} userData={{ name: 'Cylinder008_Material #280_0' }} />
        <mesh name="Box014_Material_#280_0" castShadow receiveShadow geometry={nodes['Box014_Material_#280_0'].geometry} material={materials.Material_280} position={[-0.8222306, 0.5902571, 0.2427606]} scale={[0.0763287, 0.0032372, 0.021065]} userData={{ name: 'Box014_Material #280_0' }} />
        <mesh name="Box015_Material_#280_0" castShadow receiveShadow geometry={nodes['Box015_Material_#280_0'].geometry} material={materials.Material_280} position={[2e-7, 2.4514824, -0.3317356]} rotation={[0, 0, -Math.PI]} scale={[0.0363466, 0.0006562, 0.0170761]} userData={{ name: 'Box015_Material #280_0' }} />
        <mesh name="Box016_Material_#280_0" castShadow receiveShadow geometry={nodes['Box016_Material_#280_0'].geometry} material={materials.Material_280} position={[2e-7, -2.0438951, 0.3338431]} scale={0.0085594} userData={{ name: 'Box016_Material #280_0' }} />
        <mesh name="Box017_Material_#280_0" castShadow receiveShadow geometry={nodes['Box017_Material_#280_0'].geometry} material={materials.Material_280} position={[2e-7, -2.3542653, -0.1650503]} scale={[0.0363466, 0.0006562, 0.0170761]} userData={{ name: 'Box017_Material #280_0' }} />
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_PATH)
