/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/simple_low_poly_character.glb --output src/game/models/SimpleLowPolyCharacter.tsx --root public --keepnames --keepgroups --meta --shadows --precision 7 --types 
Author: PIXELOKAY (https://sketchfab.com/PIXELOKAY)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-low-poly-character-5ee952af02634ffeab649ab9fba66bfb
Title: Simple Low Poly Character
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

export const MODEL_PATH = '/assets/simple_low_poly_character.glb'

type GLTFResult = GLTF & {
  nodes: {
    Human_full_Material003_0: THREE.Mesh
    Human_full_Material002_0: THREE.Mesh
    Human_full_Material005_0: THREE.Mesh
    Human_full_Material004_0: THREE.Mesh
    Human_full_Material006_0: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF(MODEL_PATH) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} userData={{ name: 'Sketchfab_model' }}>
          <group name="f2380100afcb47e1afbc053e76faf38dfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01} userData={{ name: 'f2380100afcb47e1afbc053e76faf38d.fbx' }}>
            <group name="RootNode" userData={{ name: 'RootNode' }}>
              <group name="Human_full" rotation={[-Math.PI / 2, 0, 0]} scale={100} userData={{ name: 'Human full' }}>
                <mesh name="Human_full_Material003_0" castShadow receiveShadow geometry={nodes.Human_full_Material003_0.geometry} material={materials['Material.003']} userData={{ name: 'Human full_Material.003_0' }} />
                <mesh name="Human_full_Material002_0" castShadow receiveShadow geometry={nodes.Human_full_Material002_0.geometry} material={materials['Material.002']} userData={{ name: 'Human full_Material.002_0' }} />
                <mesh name="Human_full_Material005_0" castShadow receiveShadow geometry={nodes.Human_full_Material005_0.geometry} material={materials['Material.005']} userData={{ name: 'Human full_Material.005_0' }} />
                <mesh name="Human_full_Material004_0" castShadow receiveShadow geometry={nodes.Human_full_Material004_0.geometry} material={materials['Material.004']} userData={{ name: 'Human full_Material.004_0' }} />
                <mesh name="Human_full_Material006_0" castShadow receiveShadow geometry={nodes.Human_full_Material006_0.geometry} material={materials['Material.006']} userData={{ name: 'Human full_Material.006_0' }} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(MODEL_PATH)
