/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/small_plane.glb --output src/game/models/SmallPlane.jsx --root public --keepnames --keepgroups --meta --shadows --precision 7 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/small_plane.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <group name="small_plane" userData={{ name: 'Small Plane', data: 'scenario', default: 'true', desc_title: 'Small Plane', desc_content: 'A minimal flat starting map.', camera_angle: 0 }}>
          <group name="player_spawn" position={[0, 0.57, 0]} userData={{ name: 'player_spawn', data: 'spawn', type: 'player' }} />
          <group name="car_spawn" position={[15, 0, 15]} userData={{ name: 'car_spawn', data: 'spawn', type: 'car' }} />
          <group name="heli_spawn" position={[-20, 0, -15]} userData={{ name: 'heli_spawn', data: 'spawn', type: 'heli' }} />
          <group name="airplane_spawn" position={[0, 0, -30]} userData={{ name: 'airplane_spawn', data: 'spawn', type: 'airplane' }} />
        </group>
        <mesh name="ground" castShadow receiveShadow geometry={nodes.ground.geometry} material={materials.concrete} userData={{ name: 'ground' }} />
        <mesh name="ground_physics" castShadow receiveShadow geometry={nodes.ground_physics.geometry} material={nodes.ground_physics.material} position={[0, -0.5, 0]} scale={[50, 0.5, 50]} userData={{ name: 'ground_physics', data: 'physics', type: 'box' }} />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/small_plane.glb')
